[project]
name = "hexlet-code"
version = "0.1.0"
description = "Page analyser"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
    "validators>=0.35.0",
]
